### ISSUE TITLE
Ship ESM build

### ISSUE THREAD

**Issue by sheremet-va** [solidjs/solid-testing-library#8]
When using [Vitest](https://github.com/vitest-dev/vitest), `testing-library` imports `render` from `/dist/server.js` because it uses `require`, bypassing `exports` rules in `solid-js`.

Shipping ESM build will solve this.

**Comment by benbender** [comment]
@modderme123 @ryansolid Would it be possible to land #7 as this breaks usage of this lib completely atm.

```
TypeError: render is not a function
 ❯ Module.render node_modules/.pnpm/solid-testing-library@0.3.0_solid-js@1.4.7/node_modules/solid-testing-library/dist/index.mjs:29:10
     27|     const dispose = hydrate
     28|         ? solidHydrate(ui, container)
     29|         : solidRender(ui, container);
```

Because of this problem, there are already "fixes" in several docs/posts around which suggest to add additional `resolve.conditions` to `vite.config.ts` as a workaround (f.e. https://github.com/vitest-dev/vitest/blob/main/examples/solid/vite.config.mjs#L21). Using those "fixes", in turn, breaks latest solid-start...

Copying the code straight from this repo to my project and use it directly (without the breaking build-step) fixes the problem entirely.

**Comment by benbender** [comment]
I had a deeper look into this and opened pr #11 as a result. As it turns out, the problem goes a bit beyond the build-config of this package.

With my pr applied, the package builds clean. If I try to use the package in my test-app, vite resolves the packages correctly in a vitest-env and imports the esm-node-bundle from `solid-js/web`. But the esm-node-bundle of `solid-js/web` doesn't export `hydrate()` as this function is only available/useful in the browser. That's, even with correctly exported esm-builds of this package, this package breaks.

I'm unsure how to fix/tackle this (besides of an explicit export in `solid-js/web` for jest/happy-dom`-environments...

**Comment by benbender** [comment]
As a temporary fix I landed on adding: 

```
resolve: {
    conditions: process.env["VITEST"] ? ["browser"] : [],
},
````

into my project's `vite.config.ts`

**Comment by atk** [comment]
Fixed with https://github.com/solidjs/solid-testing-library/pull/21
